#define MSG_VAL_LEN 16
#define CLIENT_Q_NAME_LEN 16
#define QUERY_TYPE_LEN 16
#define MSG_TYPE_LEN 16

#define COURSE_NAME_LEN 16
#define TEACHER_NAME_LEN 16

#define MAX_ARGS 10

#define SERVER_QUEUE_NAME "/server_msgq"
#define QUEUE_PERMISSIONS 0660
#define MAX_MESSAGES 10
#define MAX_MSG_SIZE sizeof(client_msg_t)
#define MSG_BUFFER_SIZE (MAX_MSG_SIZE * MAX_MESSAGES)


#define ADD_COURSE "ADD_COURSE"
#define DELETE_COURSE "DELETE_COURSE"
#define ADD_TEACHER "ADD_TEACHER"
#define DELETE_TEACHER "DELETE_TEACHER"
#define ASSIGN_TEACHER "ASSIGN_TEACHER"

#define SUCCESS 200
#define COURSE_DUPLICATE 401
#define COURSE_NOT_EXISTS 402
#define MAX_COURSE_FULL 403
#define MIN_COURSE_REQD 404
#define TEACHER_DUPLICATE 410
#define TEACHER_NOT_EXISTS 411
#define MAX_TEACHER_FULL 412
#define MIN_TEACHER_REQD 413
#define ERROR 500

#define GREEN "\033[0;32m"
#define RED "\033[1;31m"
#define BLUE "\033[0;34m"
#define RESET "\033[0m"